apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  AUTH_SECRET: 'replace-me-in-production-with-a-real-secret'
  AUTH_BASE_URL: 'https://mydevtime.com'
  TRUSTED_ORIGINS: 'https://mydevtime.com'
